wri/earth-dashboard

- components/admin/data/widgets/form/component.js
- components/admin/data/widgets/form/constants.js
- components/admin/data/widgets/form/preview/component.js
- components/admin/data/widgets/form/preview/index.js
- components/admin/data/widgets/form/preview/styles.scss
- components/admin/data/widgets/form/steps/Step1.js
- components/admin/data/widgets/form/styles.scss
- components/widgets/combined/component.js
- components/widgets/combined/index.js
- components/widgets/combined/styles.scss
- layout/app/home/component.js
This PR adds support for the new "combined" widget type.
Check this widget as an example: http://localhost:9000/admin/data/widgets/b11302e2-9526-4a86-a4f1-f27c54c68a6b/edit?dataset=47dc1a1b-2c91-4d69-b04e-ea8c4561e2b5
> Back office: combined widget support

- components/widgets/dynamic-text/component.js
This PT adds support for parameter-specific styles in dynamic text widgets.
Check this URL as an example: http://localhost:9000/admin/data/widgets/8383ea30-1166-415d-879f-51e0e8e353c6/edit?dataset=47dc1a1b-2c91-4d69-b04e-ea8c4561e2b5
> Dynamic text widgets: support for parameter-specific styles

- components/admin/data/widgets/form/constants.js
- components/admin/data/widgets/form/preview/component.js
- components/admin/data/widgets/form/steps/Step1.js
- components/admin/data/widgets/form/styles.scss
- components/widgets/news/component.js
- components/widgets/news/constants.js
- components/widgets/news/guardian-news/component.js
- components/widgets/news/guardian-news/index.js
- components/widgets/news/guardian-news/styles.scss
- components/widgets/news/index.js
- components/widgets/news/mongabay-news/component.js
- components/widgets/news/mongabay-news/index.js
- components/widgets/news/mongabay-news/styles.scss
- components/widgets/news/styles.scss
- package.json
- yarn.lock
> Support for initial version of news widgets

- components/admin/data/widgets/form/component.js
- components/admin/data/widgets/form/constants.js
- components/admin/data/widgets/form/preview/component.js
- components/admin/data/widgets/form/steps/Step1.js
- components/admin/data/widgets/pages/show/component.js
- components/widgets/combined/component.js
- components/widgets/combined/styles.scss
- components/widgets/metadata/form/MetadataForm.js
- components/widgets/metadata/form/steps/Step1.js
- components/widgets/news/guardian-news/styles.scss
- layout/app/home/component.js
- layout/app/home/styles.scss
> Highlighted widgets, first implementation

- components/admin/data/widgets/form/constants.js
- components/widgets/dynamic-text/component.js
- package.json
- yarn.lock
This PR adds support for specific formats per parameter.
More info about the widget structure can be found [here](https://docs.google.com/document/d/1w1fDIG7eDdgHA6KjJTLSA2CWcg_Ls51gA_GTrW7u_xs/edit#heading=h.p5vwzm3gf4zp)
Check the following widget as an example: http://localhost:9000/admin/data/widgets/8383ea30-1166-415d-879f-51e0e8e353c6/edit?dataset=47dc1a1b-2c91-4d69-b04e-ea8c4561e2b5
> Dynamic text widgets: support specific formats per parameter (including date+time)

- .env.sample
- components/admin/data/datasets/pages/list/component.js
- components/admin/data/datasets/pages/list/styles.scss
- components/admin/data/widgets/form/component.js
- components/admin/data/widgets/form/index.js
- components/admin/data/widgets/form/preview/component.js
- components/admin/data/widgets/form/steps/Step1.js
- components/admin/table-filters/component.js
- components/datasets/table/component.js
- components/datasets/table/td/name/component.js
- components/widgets/combined/component.js
- components/widgets/dynamic-text/component.js
> Back office: show RW datasets + allow the creation of widgets built from RW datasets

- index.js
- layout/app/home/component.js
- layout/app/home/constants.js
- layout/app/home/styles.scss
- layout/layout/layout-app/component.js
- package.json
- yarn.lock
> Homepage: first implementation of background particles

- layout/app/home/component.js
- layout/app/home/homepage.module.scss
- layout/app/topic/data/dive-into-the-data-section/component.js
- package.json
- yarn.lock
> Add Biodiversity link to homepage

- layout/app/topic/data/climate/scrolly-telling/climate-scrolly-telling.module.scss
- layout/app/topic/data/climate/scrolly-telling/component.js
- layout/app/topic/data/climate/scrolly-telling/constants.js
- package.json
- yarn.lock
> Climate clock

- components/admin/data/widgets/form/constants.js
- components/admin/data/widgets/form/steps/component.js
- components/widgets/combined/component.js
- components/widgets/dynamic-text/component.js
- components/widgets/preview/component.js
- components/widgets/source-box/component.js
- components/widgets/source-box/index.js
- components/widgets/source-box/source-box.module.scss
- components/widgets/static-text/component.js
- components/widgets/static-text/static-text-widget.module.scss
- css/_base.scss
- layout/app/topic/component.js
- layout/app/topic/data/climate/scrolly-telling/component.js
- layout/app/topic/topic.module.scss
- public/static/data/TopicPagesData.json
> Indicator widgets: source box

- public/static/data/TopicPagesData.json
Updated widget IDs for new widgets, changed the order widgets appear on the page and added additional widgets.
Please explain how to test the PR: ID of a dataset, steps to reach the feature, etc.
Provide the link to the task(s), if any.
---
> Updated widget IDs and added additional widgets to topic pages

- layout/app/topic/data/freshwater/scrolly-telling/water-drop/arrow/arrow.module.scss
- layout/app/topic/data/freshwater/scrolly-telling/water-drop/arrow/component.js
- public/static/images/scrolly-telling/freshwater/arrow-down-short.svg
- public/static/images/scrolly-telling/freshwater/arrow-up-short.svg
> Freshwater story improvements

- layout/app/topic/data/ocean/scrolly-telling/constants.js
- layout/app/topic/data/ocean/scrolly-telling/islands-of-plastic/component.js
- layout/app/topic/data/ocean/scrolly-telling/islands-of-plastic/index.js
- layout/app/topic/data/ocean/scrolly-telling/islands-of-plastic/islands-of-plastic.module.scss
- layout/app/topic/data/ocean/scrolly-telling/ocean-current-box/component.js
- layout/app/topic/data/ocean/scrolly-telling/ocean-scrolly-telling.module.scss
- utils/responsive.js
> Islands of plastic: fix currents map for three different desktop sizes

- components/share/share-box/component.js
- components/share/share-box/share-box.module.scss
- layout/app/topic/data/credits-resources-section/component.js
- layout/app/topic/data/credits-resources-section/credits-resources-section.module.scss
- layout/app/topic/data/footer/component.js
- layout/app/topic/data/footer/footer.module.scss
- layout/app/topic/data/topic-data.module.scss
- pages/[topic]/data.js
> Credits and resources mobile version

- layout/app/topic/data/ocean/scrolly-telling/islands-of-plastic/islands-of-plastic.module.scss
- layout/app/topic/data/ocean/scrolly-telling/ocean-current-box/component.js
- layout/app/topic/data/ocean/scrolly-telling/ocean-current-box/ocean-current-box.module.scss
> Ocean story: mobile version for islands of plastic map

- css/_base.scss
- css/_settings.scss
- layout/app/home/component.js
- layout/app/home/homepage.module.scss
> Homepage: mobile version improvements

- layout/header/about/component.js
- layout/header/component.js
- layout/header/header.module.scss
> Homepage: mobile version fixes

- components/widgets/news/mongabay-news/component.js
- components/widgets/panel/component.js
- layout/app/home/component.js
- layout/app/topic/component.js
- layout/app/topic/data/component.js
- layout/app/topic/news/component.js
- layout/header/about/component.js
Info about the events added can be found here: https://docs.google.com/spreadsheets/d/1e29y4D-6JlC-nmqy3q2WBp1ptYT7KEdhgB-Ib0IFRQA/edit#gid=0
> GA: custom events added

- layout/app/topic/data/climate/constants.js
- layout/app/topic/data/climate/scrolly-telling/constants.js
- layout/app/topic/data/forests/constants.js
- layout/app/topic/data/freshwater/constants.js
- layout/app/topic/data/headline-section/component.js
- layout/app/topic/data/headline-section/headline-section.module.scss
- layout/app/topic/data/ocean/constants.js
- utils/topics.js
- https://www.pivotaltracker.com/story/show/176068869
- https://www.pivotaltracker.com/story/show/176068987
> Climate story: various fixes

- public/static/images/scrolly-telling/ocean/cruise-tourism.svg
- public/static/images/scrolly-telling/ocean/deep-hydrocarbons.svg
- public/static/images/scrolly-telling/ocean/deep-sea-minerals.svg
- public/static/images/scrolly-telling/ocean/desalinated-seawater.svg
- public/static/images/scrolly-telling/ocean/marine-aquaculture.svg
- public/static/images/scrolly-telling/ocean/marine-genetic-resources.svg
- public/static/images/scrolly-telling/ocean/marine-protected-areas.svg
- public/static/images/scrolly-telling/ocean/offshore-windfarms.svg
- public/static/images/scrolly-telling/ocean/shipping.svg
- public/static/images/scrolly-telling/ocean/submarine-cables.svg
> Ocean accelerating uses chart tweaks

- README.md
- config/deploy.rb
- config/deploy/production.rb
- layout/app/home/component.js
- layout/layout/layout-app/component.js
- services/data.js
- utils/share.js
This PR carries out the necessary changes to the code once we've changed the default branch from `master` to `main`.
> Updating references in the code after renaming `master` branch to `main`

- README.md
This PR adds basic information about the main branches used in this app.
> Documentation: add info about branches to README file

- .env.sample
- .github/pull_request_template.md
- README.md
- components/form/file/component.js
- components/ui/map/map-thumbnail/helper.js
- config/deploy/production.rb
- config/deploy/staging.rb
- next.config.js
- services/raster.js
- services/user.js
- utils/axios.js
- utils/fields.js
- utils/layers/LayerManager.js
- utils/widgets/WidgetHelper.js
This PR adds minimal documentation for the environment variables used in this project.
Check the `README` and `env.sample` files.
https://vizzuality.atlassian.net/browse/ED-12?atlOrigin=eyJpIjoiMzZkNWM1YTVmMTIyNGFmOWJiYTA1MDVjMzVkMjIwNjEiLCJwIjoiaiJ9
> Documentation for ENV vars

- layout/app/home/component.js
- layout/app/home/homepage.module.scss
> First iteration of null school iframe
